name: "Handle Submission"
on:
  repository_dispatch:
    types: handle-submission

jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Process input
        run: |
          node utils/actions/process-input.js
      - name: Run prettier
        run: |
          npx prettier data/**/*.json --write
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN_PERSONAL }}
          branch-suffix: random
          title: ${{ github.event.client_payload.id }} - ${{ github.event.client_payload.repo }}
          body: |
            Submitter: ${{ github.event.client_payload.user }}
            Repository: ${{ github.event.client_payload.repo }}
            > ${{ github.event.client_payload.description }}
          labels: ${{ github.event.client_payload.id }}
